import Head from "next/head";
import Layout from "../components/Layout";
import Hero from "../components/Hero";
import Services from "../components/Services";
import {client} from '../lib/client'
import Menu from "../components/Menu";
import { useStore } from "../store/store";
export default function Home({pizzas}) {
  console.log(pizzas)
  const state=useStore((state)=>state)
  const items=useStore((state)=>state.cart.pizzas.length)
  console.log(state)
  return (
        <Layout>
    <div>
        <Head>
          <title>Foodies</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/Logo.png" />
        </Head>
        {/* body */}
        <main>  
          <Hero/>
          <Services/>
          <Menu pizzas={pizzas}/>
        </main>
      </div>
        </Layout>
  );
}


export const getServerSideProps = async() =>{
  const query = '*[_type=="pizza"]';
  const pizzas = await client.fetch(query)
  return{
    props:{
      pizzas
    }
  }
}

